### PR TITLE
Allow developers to control job display names in Hangfire

### PR DESCRIPTION
**Pull request by rasmus**
Developers can implement a custom `IJobDisplayNameBuilder` and control how a job display name is created.

@ylbillyli Would something like this work for #205?

### CODE REVIEW

**Comment by ylbillyli** [comment]
So we just have to implement the IJobDisplayNameBuilder and then can build the job name ourselves? Nice solution. In my own project, I have tried to create new IJobRunner interface myself with the DisplayName attribute and then replaced the IJobScheduler implementation to use my IJobRunner to get around. But would prefer to upgrade to this when it is available.

**Comment by ylbillyli** [comment]
Ahh, one more problem, best if we could make `JobDisplayNameBuilder.GetDisplayNameAsync` generic to customise individual job name which then would be perfect.

something like 
`GetDisplayNameAsync<TJob>(TJob job, JobDefinition jobDefinition, CancellationToken cancellationToken )`

Which then I can build the job name using properties in job like 
`return $"{jobDefinition.Name} for Client {job.ClientId}"'

**Comment by rasmus** [comment]
@ylbillyli Making it `GetDisplayNameAsync` generic would not make it easier as the service would still be resolved once as the generic isn't on the interface. Making the interface would force you to register a name build for every job and I would argue that this would be too cumbersome compared to simple implementing one.

The idea is, that `GetDisplayNameAsync` allows you to build whatever you would like to use for job names. The default will use the job definition name and version and thus providing a sensible default.

If you choose to implement your own, then you could inspect the job properties or select to simple do the convention that the job title is the `ToString()` of a job.

**Comment by rasmus** [comment]
image

**Comment by ylbillyli** [comment]
Cool. `GetDisplayNameAsync` takes the IJob. I wasn't sure that the overridden ToString() on the actual job can still be called even it is converted to the interface IJob inside `GetDisplayNameAsync`. Just now linqpad proved it does work! I agree yours would be one of the cleanest solution to my problem.

**Pull request merged**
