### PR TITLE
v0: Fixes Cake Build and Upgrades Dependencies

### PR DESCRIPTION
**Pull request by Jaben**
* Updated MongoDB to 2.28.
* Updated newtonsoft.json to 13.0.3
* Updated Npgsql to 4.1.14
* Updated Owin to 4.2.2
* Updated System.Data.SqlClient to 4.8.6

I updated the cake build, so hopefully that works again.

### CODE REVIEW

**Comment by Jaben** [comment]
@rasmus this should fix v0 branch builds.

**Comment by Jaben** [comment]
This is a little broken in that the packed Nugets will target the latest EventFlow -- not v0.83.

**Comment by rasmus** [comment]
@Jaben what's the recommendation here? I haven't touched the v0 code base in a long while

**Comment by Jaben** [comment]
> @Jaben what's the recommendation here? I haven't touched the v0 code base in a long while

A new version of "EventFlow v0" should be released -- and then I'd add a hard reference to that new build version of the v0 branch:

image

**Comment by Jaben** [comment]
I'll go ahead and update this PR to support.

**Comment by rasmus** [comment]
I'm working on getting a GHA runner up and running for EventFlow that has Docker properly configured (Linux containers).

**Comment by rasmus** [comment]
Thanks for this ❤️ it really help to get it up and v0 running again. Closing this as I tried to replicate the minimum needed in #1054 and that is now merged. It also remove Cake

**Comment by Jaben** [comment]
> Thanks for this ❤️ it really help to get it up and v0 running again. Closing this as I tried to replicate the minimum needed in #1054 and that is now merged. It also remove Cake

Absolutely! Thank you!

**Pull request closed without merging**
