### PR TITLE
Make serialization scheme more generic

### PR DESCRIPTION
**Pull request by tedvanderveen**
At the moment, quite a few implementation in the library are tightly coupled to JSON de/serialization.
For my current project, I need to use a more compact binary serialized scheme.
This PR makes event serialization scheme more generic, and allows for dropping in binary serialization.

This adds support for using for example Protobuf of BSON serialization of events.

### CODE REVIEW

**Comment by tedvanderveen** [comment]
Hi @rasmus, looks like this PR is ready for review (AppVeyor is still running at the moment).
There should be no changes to the library's existing public APIs.
Looking forward to your feedback!

**Comment by tedvanderveen** [comment]
@rasmus looks like appveyor timed out, can you restart the build please?

**Comment by tedvanderveen** [comment]
> @rasmus looks like appveyor timed out, can you restart the build please?

@rasmus added a missing newline at end of a file, to trigger new build ;-)

**Comment by tedvanderveen** [comment]
@rasmus the appveyor build timed out again (after 1 hour). Does this happen more often? Can you see more details maybe on what causes it to time out?

**Comment by rasmus** [comment]
Normally it doesn't, I'll have a look this evening

**Comment by rasmus** [comment]
Usually its the RabbitMQ tests that die, this seems a bit odd.

**Comment by rasmus** [comment]
While I do like the cleanup, this change has several braking changes thus we'll have to wait until a major release.

While 0.x is technically a beta version, many rely in the current APIs and I try not to do any API breaking changes. I know that there are plenty companies out there that have implemented their own event store to better suit their infrastructure.

**Pull request closed without merging**
