### PR TITLE
Upgrade of Hangfire implementation to support V1

### PR DESCRIPTION
**Pull request by nicolaj-hartmann**

### CODE REVIEW

**Comment by nicolaj-hartmann** [comment]
@rasmus is there something i'm missing ? :)

**Comment by rasmus** [comment]
I'll have a look this evening On 20 Feb 2024, at 12.43, Nicolaj Helmer Hartmann ***@***.***> wrote:﻿
@rasmus is there something i'm missing ? :)

**Comment by rasmus** [comment]
Seems like the build failed due to a lacking update

**Comment by nicolaj-hartmann** [comment]
@rasmus  are you talking about the same package System.Data.SqlClient? or?

**Comment by rasmus** [comment]
Hi @nicolaj-hartmann I'll get this merged

**Pull request merged**
