### PR TITLE
Aggregate ID

### PR DESCRIPTION
**Pull request by rasmus**

### CODE REVIEW

**Comment by rasmus** [comment]
@MartinHave What do you think about this solution?

**Comment by MartinHave** [comment]
@rasmus Nice one.

* We should consider the name ```IAggregateId``` What about entities and such? Whould ```IIdentity``` be a better suited name?

* Why do we want to limit the input to the identity with the name prefix? Is it really necessary? I understand the idea with descriptive ids. Can we simplify?

**Comment by rasmus** [comment]
@MartinHave The provided implementation `AggregateId` is merely a generic ID that is "good enough" for most, you can provide another implementation if you want as it merely needs to implement `IAggregateId`.

**Comment by rasmus** [comment]
@MartinHave I considered `IIdentity` but my OCD couldn't handle the double `I`. But if you have a good argument why `IIdentity` is better, then I'm OK with that.

**Pull request merged**
