### PR TITLE
System.Text.Json support

### PR DESCRIPTION
**Pull request by Yaevh**
System.Text.Json (#678)

### CODE REVIEW

**Comment by rasmus** [comment]
Build is broken, I'll have a look

**Comment by Yaevh** [comment]
@rasmus I'ver fixed the tests, can you take a look?

System.Text.Json has two basic limitations compared to Netwonsoft.Json:
1. System.Text.Json treats empty JSON as invalid and throws JsonException; Newtonsoft.Json deserializes it to null
2. Newtonsoft.Json can deserialize enum from both int value and name; System.Text.Json handles int value only

As a result, tests of System.Text.Json do not cover all the aspects covered by Newtonsoft.Json. I don't however think that those two features of Newtonsot.Json are used anywhere by EventFlow.

**Comment by rasmus** [comment]
This is great @Yaevh there's still some evaluation if one of the JSON support should be moved to a separate NuGet package (maybe Newtonsoft), but getting this in will make it a whole log easier.

**Comment by Yaevh** [comment]
Regardless of the outcome of #876, could you please merge this PR? We can always extract the code to a different project afterwards, and I'm avaliable to do this if needed :)

BTW, I believe there are no breaking changes in this PR, so maybe we could add `System.Text.Json` support to V0 already?

**Comment by rasmus** [comment]
I'll have a look

**Comment by rasmus** [comment]
Regardless if this is added or not, adding the `SystemTextJsonSerializer` class to your own project is still possible as this operates on public interfaces.

**Pull request closed without merging**
