### PR TITLE
Move the MSSQL helper out of EventFlow

### PR DESCRIPTION
**Pull request by rasmus**

### CODE REVIEW

**Comment by rasmus** [comment]
@JC008 I moved the MSSQL helper out in a completely separate project. Would this fix the #104 or are you missing more?

I have a few other things from a private repository I'll move there at some point.

**Comment by JC008** [comment]
@rasmus - Nice idea, you test helpers in EventFlow are well designed, extremely useful and can be standalone a project. I would suggest:

1. Partition the Helpz libraries based on dependacies e.g. `Helpz.MsSqlServer`, `Helpz.NUnit`, `Helpz.Postgresql`, `Helpz.TimeAndDate`, `Helpz.Sqlite`
2. Make __Helpz__ a top level organization in GitHub (same for __EventFlow__)

Here is a __LONG__ example of my mod to your 'TestFor' class which I have placed in a shared test helper library for all projects:

```c#
using Moq;
using NUnit.Framework;
using Ploeh.AutoFixture;
using Ploeh.AutoFixture.AutoMoq;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Anvil.EventFlow.TestHelpers.UnitTests
{
    public class Test
    {
        protected IFixture Fixture { get; private set; }

        public T A<T>() => Fixture.Create<T>();

        public Mock<T> InjectMock<T>(params object[] args)
            where T : class
        {
            var m = new Mock<T>(args);
            Fixture.Inject(m.Object);
            return m;
        }

        public List<T> Many<T>(int count) => Fixture.CreateMany<T>(count).ToList();

        #region Setup

        [TestFixtureSetUp]
        public void SetupFixtureForTest()
        {
            Fixture = new Fixture()
                .Customize(new AutoMoqCustomization());
        }

        #endregion Setup
    }

    public class Test<T> : Test
        where T : class
    {
        private Mock<T> _mock;
        private T _sut;

        protected virtual Mock<T> Mock
        {
            get
            {
                if (_sut != null) throw new InvalidOperationException("cannot mock after sut has been called");
                return _mock ?? (_mock = Fixture.Create<Mock<T>>());
            }
        }

        protected virtual T Sut => _mock?.Object ?? (_sut ?? (_sut = Fixture.Create<T>()));

        #region TearDown

        [TearDown]
        public void TearDownAll()
        {
            _mock = null;
            _sut = null;
        }

        #endregion TearDown
    }

    public class Test<TSubject, TFixture> : Test<TSubject>
        where TSubject: class
        where TFixture: ICustomization, new()
    {
        [TestFixtureSetUp]
        public void FixtureSetupForSut()
        {
            Fixture.Customize(new TFixture());
        }
    }

    public class Test<TSubject, TFixture1, TFixture2> : Test<TSubject>
        where TSubject : class
        where TFixture1 : ICustomization, new()
        where TFixture2 : ICustomization, new()
    {
        [TestFixtureSetUp]
        public void FixtureSetupForSut()
        {
            Fixture.Customize(new TFixture1());
            Fixture.Customize(new TFixture2());
        }
    }

    public class Test<TSubject, TFixture1, TFixture2, TFixture3> : Test<TSubject>
        where TSubject : class
        where TFixture1 : ICustomization, new()
        where TFixture2 : ICustomization, new()
        where TFixture3 : ICustomization, new()
    {
        [TestFixtureSetUp]
        public void FixtureSetupForSut()
        {
            Fixture.Customize(new TFixture1());
            Fixture.Customize(new TFixture2());
            Fixture.Customize(new TFixture3());
        }
    }

    public class Test<TSubject, TFixture1, TFixture2, TFixture3, TFixture4> : Test<TSubject>
        where TSubject : class
        where TFixture1 : ICustomization, new()
        where TFixture2 : ICustomization, new()
        where TFixture3 : ICustomization, new()
        where TFixture4 : ICustomization, new()
    {
        [TestFixtureSetUp]
        public void FixtureSetupForSut()
        {
            Fixture.Customize(new TFixture1());
            Fixture.Customize(new TFixture2());
            Fixture.Customize(new TFixture3());
            Fixture.Customize(new TFixture4());
        }
    }

    public class Test<TSubject, TFixture1, TFixture2, TFixture3, TFixture4, TFixture5> : Test<TSubject>
        where TSubject : class
        where TFixture1 : ICustomization, new()
        where TFixture2 : ICustomization, new()
        where TFixture3 : ICustomization, new()
        where TFixture4 : ICustomization, new()
        where TFixture5 : ICustomization, new()
    {
        [TestFixtureSetUp]
        public void FixtureSetupForSut()
        {
            Fixture.Customize(new TFixture1());
            Fixture.Customize(new TFixture2());
            Fixture.Customize(new TFixture3());
            Fixture.Customize(new TFixture4());
            Fixture.Customize(new TFixture5());
        }
    }
}
```

Some example Fixtures:

```c#
namespace Membership.Tests.Fixtures
{
    public class EventFlowOptionsFixture : ICustomization
    {
        public void Customize(IFixture fixture)
        {
            fixture.Customize<IResolver>(x => x.FromFactory(() =>
            {
                var eventFlowOptions = EventFlowOptions.New;
                SetupFixture(eventFlowOptions);
                return eventFlowOptions.CreateResolver();
            }));
        }

        protected virtual void SetupFixture(EventFlowOptions eventFlowOptions)
        {
        }
    }
}
```
And

```c#
using EventFlow;
using EventFlow.Extensions;

namespace Membership.Tests.Fixtures
{
    public class ResolverFixture : EventFlowOptionsFixture
    {
        protected override void SetupFixture(EventFlowOptions eventFlowOptions)
        {
            eventFlowOptions
                .UseResolverAggregateRootFactory();
        }
    }
}
```

And
```c#
using Anvil.EventFlow.TestHelpers.Values;
using Membership.Registration;
using Ploeh.AutoFixture;

namespace Membership.Tests.Fixtures
{
    public class WithAccountApplicationForBob : ICustomization
    {
        public void Customize(IFixture fixture)
        {
            fixture.Customize<AccountApplication>(x => x.FromFactory(() =>
            {
	            // ReSharper disable once ConvertToLambdaExpression
	            return new AccountApplication(BobJones.EmailAddress,
		            BobJones.FirstName,
		            BobJones.LastName,
		            BobJones.Password,
                    fixture.Create<RegistrationOptions>());
            }));
        }
    }
}
```

Used like this:

```c#
using Anvil.EventFlow.TestHelpers.UnitTests;
using Anvil.EventFlow.TestHelpers.Values;
using FluentAssertions;
using Membership.Tests.Fixtures;
using NUnit.Framework;
using System;

namespace Membership.Tests.AccountTests.UnitTests
{
    internal class AccountIdTests 
        : Test<Account.AccountId, WithAccountIdForBob>
    {

        [Test]
        [Category("Unit Tests")]
        public void AcceptsValidEmail()
        {
            // act
            Action act = () => Account.AccountId.New(BobJones.EmailAddress);

            // assert
            act.ShouldNotThrow();
        }

        [Test]
        [Category("Unit Tests")]
        public void AddsPrefix()
        {
            // act
	        var result = Sut.Value;

            // assert
            result.Should().StartWith("account-");
        }

        [Test]
        [Category("Unit Tests")]
        public void RejectsInValidEmail()
        {
            // act
            Action act = () => Account.AccountId.New(A<string>());

            // assert
            act.ShouldThrow<Exception>();
        }
    }
}
```

**Comment by JC008** [comment]
Another adaption of you configuration code, note the failure check before dropping the test DB.

```c#
using Anvil.EventFlow.TestHelpers.Configurations;
using EventFlow;
using NUnit.Framework;

namespace Membership.Tests.Configurations
{
    internal class DefaultConfiguration : SQLServerConfiguration
    {
        public override void Configure(EventFlowOptions eventFlowOptions)
        {
            base.Configure(eventFlowOptions);
            Module.Register(eventFlowOptions);
        }

        public override void Setup()
        {
            base.Setup();
            DatabaseMigrator.MigrateDatabaseUsingEmbeddedScripts(Module.Assembly);
        }

        public override void TearDown()
        {
            base.TearDown();
            if (TestContext.CurrentContext.Result.Status != TestStatus.Failed)
            {
                TestDatabase.Dispose();
            }
        }
    }
}

```

**Comment by rasmus** [comment]
@JC008 Thank you for sharing the code, I'll go through it in depth this weekend.

I think EventFlow as a organization is a good idea and something I considered early on, but as https://github.com/eventflow is already taken, although empty, and I have no means of contacting the owner I have been stuck at finding an alternative name.

As for the Helpz project, I have several helpers that I will move out of private repositories soon. I have been meaning to do so, but just needed the push.

**Comment by JC008** [comment]
@rasmus Re https://github.com/eventflow, have you contacted GitHub and inquired whether they would consider placing you in touch with the owner or relay a message to enable you appeal to the owner for a transfer of project name?

**Comment by rasmus** [comment]
@JC008 Good point, I have made the request

**Pull request merged**
